[mapper]
config = "config.toml"
device = "mastu"

[run]
default_shot = 47125

[data_sources.UDA]
# package = "tokamunch-pyuda-datasource"
plugin = "pyuda"
enabled = true
args.host = "uda2.hpc.l"
args.port = 59876
args.plugin_name = "UDA"

[data_sources.GEOMETRY]
# plugin = "tokamunch-pyuda-datasource"
plugin = "pyuda"
args.host = "uda2.hpc.l"
args.port = 59876
args.plugin_name = "GEOMETRY"
